export interface Movie {
  id: number;
  title: string;
  description: string;
  genre: string[];
  year: number;
  rating: number;
  director: string;
  cast: string[];
  runtime: number; 
  country: string;
  imageUrl: string;
  bannerUrl: string;
  trailerUrl: string;
}

export const genres = ['درام', 'جنایی', 'اکشن', 'ماجراجویی', 'فانتزی', 'علمی-تخیلی', 'هیجان‌انگیز', 'انیمیشن', 'رازآلود', 'کمدی'];

const basePath = '/movie-app';

export const movies: Movie[] = [
  {
    id: 1,
    title: 'رستگاری در شاوشنک',
    description: 'دو مرد زندانی در طی چندین سال با هم پیوند می‌خورند و از طریق اعمال شرافتمندانه به دنبال تسلی و رستگاری نهایی هستند.',
    genre: ['درام'],
    year: 1994,
    rating: 9.6,
    director: 'فرانک دارابونت',
    cast: ['تیم رابینز', 'مورگان فریمن', 'باب گانتون'],
    runtime: 142,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/The-Shawshank-Redemption-1994.webp`,
    bannerUrl: `${basePath}/images/The-Shawshank-Redemption-1994.webp`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/1wmhJ/vt/frame',
  },
  {
    id: 2,
    title: 'پدرخوانده',
    description: 'پدرسالار پیر یک سلسله جنایتکار سازمان‌یافته، کنترل امپراتوری مخفی خود را به پسر خود منتقل می‌کند.',
    genre: ['درام', 'جنایی'],
    year: 1972,
    rating: 9,
    director: 'فرانسیس فورد کوپولا',
    cast: ['مارلون براندو', 'آل پاچینو', 'جیمز کان'],
    runtime: 175,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/the-godfather.jpg`,
    bannerUrl: `${basePath}/images/the-godfather.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/iyj4f7y/vt/frame',
  },
  {
    id: 3,
    title: 'شوالیه تاریکی',
    description: 'وقتی تهدیدی به نام جوکر ویرانی و هرج و مرج را بر سر مردم گاتهام نازل می‌کند، بتمن باید یکی از بزرگترین آزمون‌های روانی و فیزیکی خود را برای مبارزه با بی‌عدالتی بپذیرد.',
    genre: ['اکشن', 'جنایی', 'درام'],
    year: 2008,
    rating: 9.0,
    director: 'کریستوفر نولان',
    cast: ['کریستین بیل', 'هیث لجر', 'آرون اکهارت'],
    runtime: 152,
    country: 'آمریکا / بریتانیا',
    imageUrl: `${basePath}/images/the-dark-knight.jpg`,
    bannerUrl: `${basePath}/images/the-dark-knight.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/i39sd58/vt/frame',
  },
  {
    id: 4,
    title: 'ارباب حلقه‌ها: بازگشت پادشاه',
    description: 'گاندالف و آراگورن ارتش دنیای انسان‌ها را در برابر ارتش سائورون رهبری می‌کنند تا حواس او را از فرودو و سم که با حلقه یگانه به کوه هلاکت نزدیک می‌شوند، پرت کنند.',
    genre: ['اکشن', 'ماجراجویی', 'درام'],
    year: 2003,
    rating: 9.4,
    director: 'پیتر جکسون',
    cast: ['الایجا وود', 'ویگو مورتنسن', 'ایان مک‌کلن'],
    runtime: 201,
    country: 'نیوزیلند / آمریکا',
    imageUrl: `${basePath}/images/The-Lord-of-the-Rings3.webp`,
    bannerUrl: `${basePath}/images/The-Lord-of-the-Rings3.webp`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/zbtb84m/vt/frame',
  },
  {
    id: 5,
    title: 'داستان عامه‌پسند',
    description: 'زندگی دو آدمکش مزدور، یک بوکسور، همسر یک گانگستر و یک زوج سارق خرده‌پا در داستانی با چهار قصه خشونت و رستگاری به هم گره می‌خورد.',
    genre: ['جنایی', 'درام'],
    year: 1994,
    rating: 9.1,
    director: 'کوئنتین تارانتینو',
    cast: ['جان تراولتا', 'اوما تورمن', 'ساموئل ال. جکسون'],
    runtime: 154,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/Pulp-Fiction.jpg`,
    bannerUrl: `${basePath}/images/Pulp-Fiction.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/g47ri7e/vt/frame',
  },
  {
    id: 6,
    title: 'فارست گامپ',
    description: 'ریاست‌جمهوری‌ها، جنگ ویتنام، واترگیت و دیگر رویدادهای تاریخی از نگاه مردی از آلاباما با ضریب هوشی ۷۵ آشکار می‌شوند.',
    genre: ['درام', 'کمدی'],
    year: 1994,
    rating: 8.8,
    director: 'رابرت زمکیس',
    cast: ['تام هنکس', 'رابین رایت', 'گری سینایس'],
    runtime: 142,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/Forrest-Gump.jpg`,
    bannerUrl: `${basePath}/images/Forrest-Gump.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/q6h4s/vt/frame',
  },
  {
    id: 7,
    title: 'تلقین',
    description: 'یک دزد که اسرار شرکت‌ها را از طریق فناوری اشتراک رویا می‌دزدد، مأموریت کاشتن یک ایده در ذهن یک مدیرعامل را بر عهده می‌گیرد.',
    genre: ['اکشن', 'ماجراجویی', 'علمی-تخیلی'],
    year: 2010,
    rating: 9.5,
    director: 'کریستوفر نولان',
    cast: ['لئوناردو دی‌کاپریو', 'جوزف گوردون-لویت', 'الیوت پیج'],
    runtime: 148,
    country: 'آمریکا / بریتانیا',
    imageUrl: `${basePath}/images/inception_image.jpg`,
    bannerUrl: `${basePath}/images/inception_image.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/f018sk4/vt/frame',
  },
  {
    id: 8,
    title: 'ماتریکس',
    description: 'یک هکر کامپیوتر متوجه می‌شود که دنیای او یک واقعیت شبیه‌سازی شده است و به شورشی علیه ماشین‌هایی که او و تمام بشریت را کنترل می‌کنند، می‌پیوندد.',
    genre: ['اکشن', 'علمی-تخیلی'],
    year: 1999,
    rating: 9.3,
    director: 'خواهران واچوفسکی',
    cast: ['کیانو ریوز', 'لارنس فیشبرن', 'کری-ان ماس'],
    runtime: 136,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/The-Matrix-poster.jpg`,
    bannerUrl: `${basePath}/images/The-Matrix-poster.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/john8a6/vt/frame',
  },
  {
    id: 9,
    title: 'میان‌ستاره‌ای',
    description: 'تیمی از کاوشگران از طریق یک کرم‌چاله در فضا سفر می‌کنند تا اطمینان حاصل کنند که بشریت آینده‌ای دارد.',
    genre: ['ماجراجویی', 'درام', 'علمی-تخیلی'],
    year: 2014,
    rating: 8.7,
    director: 'کریستوفر نولان',
    cast: ['متیو مک‌کانهی', 'ان هتوی', 'جسیکا چستین'],
    runtime: 169,
    country: 'آمریکا / بریتانیا',
    imageUrl: `${basePath}/images/inter-stellar.jpg`,
    bannerUrl: `${basePath}/images/inter-stellar.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/LuJs1/vt/frame',
  },
  {
    id: 10,
    title: 'شهر اشباح',
    description: 'در حین نقل مکان به حومه شهر، یک دختر ۱۰ ساله وارد دنیایی می‌شود که توسط خدایان، جادوگران و ارواح اداره می‌شود و انسان‌ها به هیولا تبدیل می‌شوند.',
    genre: ['انیمیشن', 'ماجراجویی', 'فانتزی'],
    year: 2001,
    rating: 9.2,
    director: 'هایائو میازاکی',
    cast: ['رومی هیراگی', 'ایرو ماری', 'میو ایرینو'],
    runtime: 125,
    country: 'ژاپن',
    imageUrl: `${basePath}/images/apirited-away.webp`,
    bannerUrl: `${basePath}/images/apirited-away.webp`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/peURK/vt/frame',
  },
    {
    id: 11,
    title: 'انگل',
    description: 'حرص و تبعیض طبقاتی رابطه تازه‌شکل‌گرفته بین خانواده ثروتمند پارک و خانواده فقیر کیم را تهدید می‌کند.',
    genre: ['کمدی', 'درام', 'هیجان‌انگیز'],
    year: 2019,
    rating: 8.5,
    director: 'بونگ جون-هو',
    cast: ['سونگ کانگ-هو', 'لی سون-کیون', 'چو یو-جونگ'],
    runtime: 132,
    country: 'کره جنوبی',
    imageUrl: `${basePath}/images/Parasyte.webp`,
    bannerUrl: `${basePath}/images/Parasyte.webp`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/h00a939/vt/frame',
  },
  {
    id: 12,
    title: 'سکوت بره‌ها',
    description: 'یک کارآموز جوان اف‌بی‌آی باید از یک قاتل زنجیره‌ای زندانی برای دستگیری قاتل دیگری که پوست قربانیانش را می‌کند، کمک بگیرد.',
    genre: ['جنایی', 'درام', 'هیجان‌انگیز'],
    year: 1991,
    rating: 8.6,
    director: 'جاناتان دمی',
    cast: ['جودی فاستر', 'آنتونی هاپکینز', 'اسکات گلن'],
    runtime: 118,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/silence-of-the-lambs.jfif`,
    bannerUrl: `${basePath}/images/silence-of-the-lambs.jfif`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/R6eUX/vt/frame',
  },
  {
    id: 13,
    title: 'گلادیاتور',
    description: 'یک ژنرال رومی سابق پس از اینکه پسر فاسد امپراتور خانواده‌اش را به قتل می‌رساند و او را به بردگی می‌فرستد، برای انتقام به میدان بازمی‌گردد.',
    genre: ['اکشن', 'ماجراجویی', 'درام'],
    year: 2000,
    rating: 8.5,
    director: 'ریدلی اسکات',
    cast: ['راسل کرو', 'واکین فینیکس', 'کانی نیلسن'],
    runtime: 155,
    country: 'آمریکا / بریتانیا',
    imageUrl: `${basePath}/images/gladiator.jpeg`,
    bannerUrl: `${basePath}/images/gladiator.jpeg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/ssq37g0/vt/frame',
  },
  {
    id: 14,
    title: 'رفتگان',
    description: 'یک پلیس مخفی و یک جاسوس در پلیس ایالتی ماساچوست تلاش می‌کنند تا هویت یکدیگر را در حالی که به یک سندیکای جنایی ایرلندی نفوذ کرده‌اند، شناسایی کنند.',
    genre: ['جنایی', 'درام', 'هیجان‌انگیز'],
    year: 2006,
    rating: 8.5,
    director: 'مارتین اسکورسیزی',
    cast: ['لئوناردو دی‌کاپریو', 'مت دیمون', 'جک نیکلسون'],
    runtime: 151,
    country: 'آمریکا / هنگ کنگ',
    imageUrl: `${basePath}/images/departed.webp`,
    bannerUrl: `${basePath}/images/departed.webp`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/m380235/vt/frame',
  },
  {
    id: 15,
    title: 'حیثیت',
    description: 'پس از یک تراژدی وحشتناک، دو شعبده‌باز در دوران ویکتوریا درگیر رقابتی برای خلق بهترین توهم صحنه می‌شوند در حالی که برای افشای اسرار یکدیگر فداکاری می‌کنند.',
    genre: ['درام', 'رازآلود', 'علمی-تخیلی'],
    year: 2006,
    rating: 9.1,
    director: 'کریستوفر نولان',
    cast: ['کریستین بیل', 'هیو جکمن', 'اسکارلت جوهانسون'],
    runtime: 130,
    country: 'آمریکا / بریتانیا',
    imageUrl: `${basePath}/images/The-Prestige.jpg`,
    bannerUrl: `${basePath}/images/The-Prestige.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/6jIXu/vt/frame',
  },
  {
    id: 16,
    title: 'ویپلش',
    description: 'یک درامر جوان و آینده‌دار در یک هنرستان موسیقی نخبه ثبت‌نام می‌کند، جایی که رویاهایش برای بزرگی توسط مربی‌ای که از هیچ چیز برای تحقق پتانسیل یک دانش‌آموز دست نمی‌کشد، هدایت می‌شود.',
    genre: ['درام'],
    year: 2014,
    rating: 8.5,
    director: 'دیمین شزل',
    cast: ['مایلز تلر', 'جی. کی. سیمونز', 'پال رایزر'],
    runtime: 106,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/whiplash.webp`,
    bannerUrl: `${basePath}/images/whiplash.webp`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/u557g1z/vt/frame',
  },
  {
    id: 18,
    title: 'جوکر',
    description: 'در گاتهام سیتی، کمدین شکست‌خورده‌ای به نام آرتور فلک به دنبال ارتباط با دیگران است. او در چرخه‌ای از جنون و جنایت قرار می‌گیرد و با شخصیت جوکر به شهر بازمی‌گردد.',
    genre: ['جنایی', 'درام', 'هیجان‌انگیز'],
    year: 2019,
    rating: 8.4,
    director: 'تاد فلیپس',
    cast: ['واکین فینیکس', 'رابرت دنیرو', 'زازی بیتز'],
    runtime: 122,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/joker.jpg`,
    bannerUrl: `${basePath}/images/joker.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/izchue2/vt/frame',
  },
  {
    id: 19,
    title: 'بیگانگان',
    description: 'پنجاه و هفت سال پس از زنده ماندن از یک برخورد وحشتناک، الن ریپلی از خواب زمستانی بیدار می‌شود و به همراه تیمی از تفنگداران دریایی استعماری برای تحقیق به قمری که موجودات بیگانه را در آن پیدا کرده بود، بازمی‌گردد.',
    genre: ['اکشن', 'ماجراجویی', 'علمی-تخیلی'],
    year: 1986,
    rating: 8.3,
    director: 'جیمز کامرون',
    cast: ['سیگورنی ویور', 'مایکل بین', 'کری هن'],
    runtime: 137,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/alien.webp`,
    bannerUrl: `${basePath}/images/alien.webp`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/bbu52lx/vt/frame',
  },
  {
    id: 20,
    title: 'وال-ای',
    description: 'در آینده‌ای دور، یک ربات کوچک جمع‌آوری زباله به طور ناخواسته وارد یک ماجراجویی فضایی می‌شود که سرنوشت بشریت را تعیین خواهد کرد.',
    genre: ['انیمیشن', 'ماجراجویی', 'علمی-تخیلی'],
    year: 2008,
    rating: 8.4,
    director: 'اندرو استنتون',
    cast: ['بن برت', 'الیسا نایت', 'جف گارلین'],
    runtime: 98,
    country: 'آمریکا',
    imageUrl: `${basePath}/images/WALL-E.jpg`,
    bannerUrl: `${basePath}/images/WALL-E.jpg`,
    trailerUrl: 'https://www.aparat.com/video/video/embed/videohash/Y4U3N/vt/frame',
  },
];